name: adminsite
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  fluent_ui: ^4.7.6
  file_picker: ^6.0.0
  dio: ^5.3.3
  path: ^1.8.3
  http_parser: ^4.0.2
  kplayer: ^0.4.2
  audioplayers: ^5.2.0
  window_manager: ^0.2.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-Bold.ttf
        - asset: assets/fonts/Arimo-BoldItalic.ttf
        - asset: assets/fonts/Arimo-Italic.ttf
        - asset: assets/fonts/Arimo-Medium.ttf
        - asset: assets/fonts/Arimo-MediumItalic.ttf
        - asset: assets/fonts/Arimo-Regular.ttf
        - asset: assets/fonts/Arimo-SemiBold.ttf
        - asset: assets/fonts/Arimo-SemiBoldItalic.ttf
    - family: InknutAntiqua
      fonts:
        - asset: assets/fonts/InknutAntiqua-Bold.ttf
        - asset: assets/fonts/InknutAntiqua-Regular.ttf
    - family: Kadwa
      fonts:
        - asset: assets/fonts/Kadwa-Bold.ttf
        - asset: assets/fonts/Kadwa-Regular.ttf
  uses-material-design: true
  assets:
   - assets/
